services:
  db:
    image: postgres:16
    container_name: postgres-db-tauranet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin1325
      POSTGRES_DB: tauranet_db
    ports:
      - "25432:5432"
    volumes:
      - tauranet-prod-db-data:/var/lib/postgresql/data
      - ./tauranet-backend/tauranet_db.sql:/docker-entrypoint-initdb.d/tauranet_db.sql

  backend:
    build:
      context: ./tauranet-backend
      dockerfile: Dockerfile
    container_name: tauranet-backend-prod
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: postgres-db-tauranet
      DB_PORT: 25432
      DB_DATABASE: tauranet_db
      DB_USERNAME: postgres
      DB_PASSWORD: pgadmin1325
    volumes:
      - ./tauranet-backend:/var/www

volumes:
  tauranet-prod-db-data:
